config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]

        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]

        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end

    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    get '/representatives/:representative_id/profile' => 'representatives#show', :as => 'show_representatives'
    get '/representatives/my_news_item/new/' => 'my_news_items#search', :as => 'search_news'
    get '/representatives/my_news_item/new/search' => 'my_news_items#search_issue', :as => 'search_news_issue'
    get '/representatives/my_news_item/new/search/:representative_id/:issue/rating' => 'my_news_items#rate_articles', :as => 'rate_articles'
    get '/representatives/my_news_item/new/search/(:representative_id)/(:issue)' => 'my_news_items#search_issue_rep', :as => 'search_news_issue_rep'
end

app/models/representative.rb
# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all
  def self.civic_api_to_representative_params(rep_info)
    reps = []
    rep_info.officials.each_with_index do |official, index|
      ocdid_temp = ''
      title_temp = ''
      city_temp = ''
      street_temp = ''
      state_temp = ''
      zip_temp = ''
      
      rep_info.offices.each do |office|
        if office.official_indices.include? index
          title_temp = office.name
          ocdid_temp = office.division_id
        end
      end
      if !official.address.nil? 
        official.address.each do |add|
          city_temp = add.city
          street_temp = add.line1
          state_temp = add.state
          zip_temp = add.zip
        end
      end
      party_temp = official.party
      photo_temp = official.photo_url 
      if(Representative.find_by(name: official.name).nil?)
      rep = Representative.create!({ name: official.name, ocdid: ocdid_temp,
          title: title_temp, city: city_temp, street: street_temp,
          state: state_temp, zip: zip_temp, party: party_temp, photo: photo_temp})
      else
        rep = Representative.find_by(name: official.name)
      end
      reps.push(rep)
    end

    reps
  end

  

end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end

  def show
    id = params[:representative_id] # retrieve representative ID from URI route
    @representatives = Representative.find(id) # look up representative by unique ID
    # will render app/views/representatives/show.<extension> by default
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
  def self.get_all
    Representatives.all
  end
end

app/views/representatives/index.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get do
            .form-group.row
                .col-md-4
                    %label.col-form-label
                        Enter a location:
                .col-md-6
                    = text_field_tag(:address, nil, class: 'form-control')

            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
    .row
        .col-md-8.offset-md-2
            .table-responsive-md.pt-5
                %table.table.table-striped.table-hover#events
                    %caption Table of Representatives
                    %thead.thead-dark
                        %tr
                            %th Name
                            %th Office
                            %th Links
                    %tbody
                        - @representatives.each_with_index do |rep, _index|
                            %tr
                                %td
                                    = link_to show_representatives_path(rep.id), class: 'btn btn-light' do
                                        = rep.name
                                %td= rep.title
                                %td
                                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                                        %i.fas.fa-newspaper
                                        News Articles

app/views/representatives/show.html.erb
<!--  app/views/representatives/show.html.erb -->
<h2>Profile : <em><%= @representatives.name %></em></h2>

<ul id="details">
  <li>
    Name:
    <%= @representatives.name %>
  </li>
  <li>
    OCD ID:
    <%= @representatives.ocdid %> 
  </li>
  <li>
    Office:
    <%= @representatives.title %> 
  </li>
  
  <li>
    Street:
    <%= @representatives.street %> 
  </li>
  <li>
    City:
    <%= @representatives.city %> 
  </li>
  <li>
    State:
    <%= @representatives.state %> 
  </li>
  <li>
    Zip:
    <%= @representatives.zip %> 
  </li>
  
  <li>
    Party:
    <%= @representatives.party %> 
  </li>
  <li>
    Photo: 
    <%- if !@representatives.photo.nil? -%>
    <%= image_tag(@representatives.photo, :alt => @representatives.photo) %>
    <%- end -%>
  </li>

</ul>