config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]

        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]

        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end

    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    get '/representatives/:representative_id/profile' => 'representatives#show', :as => 'show_representatives'
    get '/representatives/my_news_item/new/' => 'my_news_items#search', :as => 'search_news'
    get '/representatives/my_news_item/new/search' => 'my_news_items#search_issue', :as => 'search_news_issue'
    get '/representatives/my_news_item/new/search/:representative_id/:issue/rating' => 'my_news_items#rate_articles', :as => 'rate_articles'
    get '/representatives/my_news_item/new/search/(:representative_id)/(:issue)' => 'my_news_items#search_issue_rep', :as => 'search_news_issue_rep'
end

app/controllers/my_news_items_controller.rb
# frozen_string_literal: true

class MyNewsItemsController < SessionController
  before_action :set_representative, only: %i[search_issue_rep]

  before_action :set_news_item, only: %i[edit update destroy]

  def new
    @news_item = NewsItem.new
    @representative = Representative.find(:name => params[:representative_name])
    @issue = params[:issue]
  end

  def edit
    # get representative with the name
    # issue with the from the parameters
  end
  
  def search
    render :new
  end

  def search_issue
    @representative = Representative.find_by_name(params[:representative_name])
    @issue = params[:issue]
    redirect_to search_news_issue_rep_path(@representative, @issue)
  end

  def search_issue_rep
    newsapi = News.new("de90eb71b1014faca2ed961ac8b1be50")
    @news_items = newsapi.get_everything(q: params[:issue], language: "en", sortBy: 'relevancy',page: 1)
    render :new2

  end

  def rate_articles
    @ratings = params[:rating]
    @article_title = params[:articles]
    
    newsapi = News.new("de90eb71b1014faca2ed961ac8b1be50") 
    @news_items = newsapi.get_everything(q: params[:issue], searchIn: @article_title, sortBy: 'relevancy',page: 1)
    newsrating = Rating.create(params[:representative_id], @article_title, @ratings) 
    render :new
  end

  def create
    @news_item = NewsItem.new(news_item_params)
    if @news_item.save
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully created.'
    else
      render :new, error: 'An error occurred when creating the news item.'
    end
  end

  def update
    if @news_item.update(news_item_params)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully updated.'
    else
      render :edit, error: 'An error occurred when updating the news item.'
    end
  end

  def destroy
    @news_item.destroy
    redirect_to representative_news_items_path(@representative),
                notice: 'News was successfully destroyed.'
  end

  private

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def set_representatives_list
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def news_item_params
    params.require(:news_item).permit(:news, :title, :description, :link, :representative_id)
  end
end

app/views/my_news_items/_form.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :title, 'Title:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :title, { class: 'form-control', placeholder: 'Brief title of article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :link, 'Link:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :link, { class: 'form-control', placeholder: 'Link to external article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :description, 'Description:', class: 'col-form-label'
        .col-sm-10
            = text_area :news_item, :description, { class: 'form-control',
            placeholder: 'Describe the contents of the article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, 'Representative:', class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list,
            { include_blank: false, selected: representative.id },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, 'Issue:', class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, issues_list, { include_blank: 'Select an issue...' },
            class: 'form-control'
    .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/my_news_items/edit.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article (2)

app/views/my_news_items/new.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

        
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            = form_tag search_news_issue_path, method: :get do
                .form-group.row
                    .col-12
                        = select_tag :representative_name, options_for_select(Representative.all.map {|rep| [rep.name]}),
                            { prompt: 'Select a representative', class: 'form-control', id: 'actionmap-events-filter-state' }
                .form-group.row
                    .col-12
                        = select_tag :issue, options_for_select(["Free Speech", "Immigration", "Terrorism", "Social Security and Medicare", "Abortion", "Student Loans", "Gun Control", "Unemployment","Climate Change", "Homelessness", "Racism", "Tax Reform", "Net Neutrality", "Religious Freedom", "Border Security", "Minimum Wage","Equal Pay"]),
                            { prompt: 'Select an issue', class: 'form-control', id: 'actionmap-events-filter-state' }
                .actions
                    = submit_tag 'Search', class: 'btn btn-primary'

app/views/my_news_items/new2.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article 3
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-left Representative: #{@representative.name}
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-left Issue: #{params[:issue]}

= form_tag rate_articles_path, method: :get, class: 'form' do
    .form-group
        .row
            %legend.col-form-label.col-sm-12.py-1 Select an article:
            .col-sm-12
                .form-check
                    = radio_button_tag :article, @news_items[0].title, false,
                        id: 'art1-radio', class: 'form-check-input'
                    %label.form-check-label{ for: 'actionmap-events-filter-state-radio' } Title :#{@news_items[0].title}
                    <br />
                    Link: <a href="url">#{@news_items[0].url}</a>
                    <br />
                    Description: #{@news_items[0].description}
                .form-check
                    = radio_button_tag :article, @news_items[1].title, false,
                        id: 'art2-radio', class: 'form-check-input'
                    %label.form-check-label{ for: 'actionmap-events-filter-county-radio' } Title: #{@news_items[1].title}
                    <br />
                    Link: <a href="url">#{@news_items[1].url}</a>
                    <br />
                    Description: #{@news_items[1].description}
                .form-check
                    = radio_button_tag :article, @news_items[2].title, false,
                        id: 'art3-radio', class: 'form-check-input'
                    %label.form-check-label{ for: 'actionmap-events-filter-county-radio' } Title: #{@news_items[2].title}
                    <br />
                    Link: <a href="url">#{@news_items[2].url}</a>
                    <br />
                    Description: #{@news_items[2].description}
                .form-check
                    = radio_button_tag :article, @news_items[3].title, false,
                        id: 'art4-radio', class: 'form-check-input'
                    %label.form-check-label{ for: 'actionmap-events-filter-county-radio' } Title: #{@news_items[3].title}
                    <br />
                    Link: <a href="url">#{@news_items[3].url}</a>
                    <br />
                    Description: #{@news_items[3].description}
                .form-check
                    = radio_button_tag :article, @news_items[4].title, false,
                        id: 'art5-radio', class: 'form-check-input'
                    %label.form-check-label{ for: 'actionmap-events-filter-county-radio' } Title: #{@news_items[4].title}    
                    <br />
                    Link: <a href="url">#{@news_items[4].url}</a>
                    <br />
                    Description: #{@news_items[4].description}
                .form-group.row
                    .col-12
                        = select_tag :rating, options_for_select(["1","2", "3","4", "5"]),
                            { prompt: 'Select a rating', class: 'form-control', id: 'actionmap-events-filter-state' }
        .actions
            = submit_tag 'Save', class: 'btn btn-primary'